version: "3.4"

services:
  frontend:
    image: jfahrer/swarm-demo-frontend:v11
    secrets:
      - pg_secret
    env_file:
      - app.env
    labels:
      app: demo
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: app.demo.frontend
    deploy:
      replicas: 10
      update_config:
        failure_action: rollback
        parallelism: 3
        delay: 3s
        max_failure_ratio: 0.1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 1
      placement:
        constraints:
          - node.labels.region==us-west1

  db:
    image: jfahrer/swarm-demo-db:v1
    env_file:
      - db.env
    secrets:
      - pg_secret
    volumes:
      - pg-data:/var/lib/postgresql/data
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: app.demo.db
    deploy:
      resources:
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.hostname == node1

  lb:
    image: jfahrer/swarm-demo-lb:v1
    environment:
      - PROXY_UPSTREAM=frontend:8080
    ports:
      - 80:80
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: app.demo.lb
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
  pg-data:

secrets:
  pg_secret:
    file: ./pg_secret
