version: "3.4"

secrets:
  my-super-secret-key:
    external: true

  my-password:
    external: true

  other-key:
    file: ./other.key

services:
  shell:
    image: alpine:3.6
    command: tail -f /dev/null
    secrets:
      - my-super-secret-key
      - my-password
      - source: other-key
        target: foobar.key
    deploy:
      placement:
        constraints:
          - node.hostname==node1
